$(document).ready(function() {
         $('.ex_01').click(function(){
            $('.pop_01').fadeIn(); 
         });
         $('.cl_01').click(function(){
            $('.pop_01').fadeOut(); 
         });   
         $('.ex_02').click(function(){
            $('.pop_02').fadeIn(); 
         });
         $('.cl_02').click(function(){
            $('.pop_02').fadeOut(); 
         });   
        $('.ex_03').click(function(){
            $('.pop_03').fadeIn(); 
         });
         $('.cl_03').click(function(){
            $('.pop_03').fadeOut(); 
         });  
        $('.ex_04').click(function(){
            $('.pop_04').fadeIn(); 
         });
         $('.cl_04').click(function(){
            $('.pop_04').fadeOut(); 
         });   
        $('.ex_05').click(function(){
            $('.pop_05').fadeIn(); 
         });
         $('.cl_05').click(function(){
            $('.pop_05').fadeOut(); 
         });   
            
        });